[LOG]
# Optional: [INFO, DEBUG]
CONSOLE_LEVEL = INFO
FILE_LEVEL = DEBUG
# Optional: [console, file, both]
TARGET = both
FILE_PATH = logs/app.log

[EVALUATE]
TEST_FILE_PATH = data/chatflow_multi_turn_test_data.xlsx
RESULT_DIR = results
MAX_WORKERS = 1

[DIFY]
API_KEY = app-xxx
BASE_URL = xxx
# Optional: [chatflow, workflow]
APP_TYPE = chatflow

[EVAL_LLM]
#   API_BASE = http://localhost:8000/v1/chat/completions  (requests 方式)
#   API_BASE = http://localhost:8000/v1                   (openai SDK 方式)
CLIENT_METHOD = openai
API_KEY = sh-xxxxxxxxxxxxxxxxxxxxxxxx
BASE_URL = xxxxxxxxxxxxxxxxxxxxxxxx
MODEL_NAME = qwen
MAX_TOKEN = 20480
TEMPERATURE = 0
ENABLE_THINKING = False
TIMEOUT = 1200.0
MAX_RETRIES = 3
STREAM = FALSE